# Use version 3.8 to support the 'deploy.resources' key for GPU access
version: "3.8"

services:
  vinicapture:
    container_name: vinicapture
    # Build from the Dockerfile in the current directory
    image: ghcr.io/ardoviniandrea/vinicapture:latest
    ports:
      # 8993 for the All-in-One Control Panel (maps to port 80 in container)
      - "8993:80"
      # 8994 for the HLS Stream (maps to port 8994 in container)
      - "8994:8994"
    restart: unless-stopped
    
    # --- FIX: Increase shared memory size for Chrome stability ---
    # This prevents the common 'SIGTRAP' error by giving Chrome more
    # memory for inter-process communication.
    shm_size: '1gb'

    volumes:
      - vinicapture-data:/data
    
    # --- GPU HARDWARE ACCELERATION ---
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  vinicapture-data:
